version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-dvwa-web
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
  db:
    image: mysql:8.0
    container_name: my-dvwa-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: dvwa
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-dvwa-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: dvwa
      PMA_PASSWORD: dvwa
    depends_on:
      - db
volumes:
  db_data: